name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # Use env-scoped secrets in this job:
    environment: github-pages
    env:
      # Only expose values meant for the client build
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Avoid trying to use secrets on PRs from forks
      - name: Install dependencies
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        run: npm ci

      - name: Debug env
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        run: |
          echo "VITE_SUPABASE_URL length: ${#VITE_SUPABASE_URL}"
          echo "VITE_SUPABASE_ANON_KEY length: ${#VITE_SUPABASE_ANON_KEY}"

      - name: Build
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        run: npm run build

      - name: Setup Pages
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
